PREFIX glytoucan: <http://www.glytoucan.org/glyco/owl/glytoucan#>
PREFIX rocs: <http://www.glycoinfo.org/glyco/owl/relation#>
PREFIX glycan: <http://purl.jp/bio/12/glyco/glycan#>

INSERT {
  GRAPH <http://rdf.glytoucan.org/composition> {
    ?ss rocs:has_composition_with_linkage ?s.
    ?s a rocs:Monosaccharide_composition_with_linkage.
  }
}
DELETE {
  GRAPH <http://rdf.glytoucan.org/composition> {
    ?ss rocs:has_composition ?s.
    ?s a rocs:Monosaccharide_composition.
  }
}
WHERE {
  GRAPH <http://rdf.glytoucan.org/composition> {
    ?ss rocs:has_composition ?s.
    ?s a rocs:Monosaccharide_composition.
  }
}
limit 10
