PREFIX glytoucan: <http://www.glytoucan.org/glyco/owl/glytoucan#>
PREFIX rocs: <http://www.glycoinfo.org/glyco/owl/relation#>
PREFIX glycan: <http://purl.jp/bio/12/glyco/glycan#>

SELECT DISTINCT ?id ?subsumes_id
FROM <http://rdf.glytoucan.org/core>
FROM <http://rdf.glytoucan.org/topology>
FROM <http://rdf.glytoucan.org/composition>
FROM <http://rdf.glytoucan.org/basecomposition>
FROM <http://rdf.glytoucan.org/sequence/iupac_extended>
WHERE {
  VALUES ?id {"G15843XU"}
  VALUES ?has_topology { rocs:has_topology }
  VALUES ?has_composition { rocs:has_composition }
  VALUES ?has_base_composition { rocs:has_base_composition }
  OPTIONAL {
    ?s glytoucan:has_primary_id ?subsumes_id .
    ?s ?has_topology ?ht .
    ?ht glytoucan:has_primary_id ?id .
    ?ht a rocs:Glycosidic_topology .
    ?s glycan:has_glycosequence ?seq .
    ?seq glycan:has_sequence ?iupac .
  }
  OPTIONAL {
    ?s glytoucan:has_primary_id ?subsumes_id .
    ?s ?has_composition ?hc .
    ?hc glytoucan:has_primary_id ?id .
    ?hc a rocs:Monosaccharide_composition .
  }
  OPTIONAL {
    ?s glytoucan:has_primary_id ?subsumes_id .
    ?s ?has_base_composition ?hbc .
    ?hbc glytoucan:has_primary_id ?id .
    ?hbc a rocs:Base_composition .
  }
} ORDER BY ?iupac
